# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', 'tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='black_chars',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
