# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=16)),
                ('book_author', models.CharField(max_length=16)),
                ('book_transcriber', models.CharField(blank=True, max_length=16)),
                ('book_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_mark', models.CharField(blank=True, max_length=1)),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('char_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('book_notes', models.TextField(blank=True)),
                ('book_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Book')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='page_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page'),
        ),
    ]
