# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:11
#
# Migration we really don't need.  Realized we needed extra fields, which aare in 0003 migration
#
#######################################################
from __future__ import unicode_literals
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0001_initial'),
    ]
