# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:57
# Appends adds a title to existing entries that need one
#
#########################################################
from __future__ import unicode_literals

from django.db import migrations
import json

def addworktitles(apps) -> None:
    Work = apps.get_model("calligraphy", "Work")
    jsonfile = open("c-works-2.json", mode="r", encoding='utf-8')
    readfile = json.load(jsonfile)
    jsonfile.close()
    for r in readfile:
        wkid = int(r['wkid'])
        curwork = Work.objects.get(work_id=wkid)
        curwork.work_title = r['wktitle']
        curwork.save()


def import_data(apps, schemd_editor) -> None:
    addworktitles(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0001_initial'),
    ]

    operations = [ migrations.RunPython(import_data)
    ]
