# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:42
#
# Migration to import character data from c-chars.json
#
###########################################################
from __future__ import unicode_literals

import json, socket, os
from django.db import migrations, models
import django.db.models.deletion

HOSTNAME = socket.gethostname()
if HOSTNAME == 'bigArch':
    PAGES_DIR = "/home/dave/workspace/pycharm/fetch/grabbedBooks/"  #Maybe, need to double-check
    CHARS_DIR = "/home/dave/workspace/pycharm/fetch/chars"
else:
    PAGES_DIR = "/media/pages/"
    CHARS_DIR = "/media/chars/"

def read_cworks(apps) -> None:
    jsonfile = open("c-chars.json", mode="r", encoding='utf-8')
    readfile = json.load(jsonfile)
    jsonfile.close()
    Author = apps.get_model("calligraphy", "Author")
    Work = apps.get_model("calligraphy", "Work")
    Page = apps.get_model("calligraphy", "Page")
    Char = apps.get_model("calligraphy", "Character")
    for r in readfile:
        mark = r['chi_mark']
        if mark == '':
            mark = None
        auth = r['chi_author']
        if auth == '':
            auth = None
        work = r['chi_work']
        if work == '':
            work = None
        wkid = r['work_id']
        pgid = r['page_id']
        cord = r['xy_coordinates']
        x1 = cord[0]
        y1 = cord[1]
        x2 = cord[2]
        y2 = cord[3]
        charfile_1 = CHARS_DIR + wkid + '/'
        charfile_2 = pgid + '(' + x1 + ',' + y1 + ',' + x2 + ',' + y2 + ').jpg'
        filename = charfile_1 + charfile_2
        if not os.path.isfile(filename):
            Exception("cannot find", filename)
        if work is not None':
            works = Work.objects.filter(author_name=auth)
            if 1 !=len(authors) :
                print(len(authors))
                print(auth)

    Exception("brake Here")


def import_data(apps, schemd_editor):
    read_cworks(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0002_auto_20160223_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='parent_work',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='parent_author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Author'),
        ),
        migrations.RunPython(import_data)
    ]
