# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 02:38
#
# Need to allow null inputs on page and bookid.
#
####################################################
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0006_auto_20160226_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_bookid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_pageid',
            field=models.IntegerField(null=True),
        ),
    ]
