# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0008_auto_20160226_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='char_work',
        ),
    ]
