# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0010_auto_20160303_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dynesty',
            new_name='dynasty',
        ),
    ]
