# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 07:31
#
# This part replaces empty title with a non-empty placeholder
#
#########################################################
from __future__ import unicode_literals

from django.db import migrations


def fillemptytitles(apps) -> None:
    Work = apps.get_model("calligraphy", "Work")
    works = Work.objects.all()
    for work in works:
        if work.title == '':
            work.title = "?"
            work.save()


def import_data(apps, schemd_editor) -> None:
    fillemptytitles(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0011_auto_20160303_2051'),
    ]

    operations = [ migrations.RunPython(import_data)
    ]
