# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 15:46
from __future__ import unicode_literals
from django.db import migrations, models
from PIL import Image


def compute_image_size(apps) -> None:
    Page = apps.get_model("calligraphy", "Page")
    pages = Page.objects.all()
    for page in pages:
        if page.image is not None:
            cur = Image.open(page.image)
            page.image_width = cur.size[0]
            page.image_length = cur.size[1]
            cur.close()
            page.save()


def import_data(apps, schemd_editor) -> None:
    compute_image_size(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0012_auto_20160303_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(import_data)
    ]
