# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 05:49
#
# Adds small images for Models
#
#
###################################################################
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models

def addsmallimage(apps) -> None:
    Page = apps.get_model("calligraphy", "Page")
    page = Page.objects.all()
    for page in page:
        imgsplt = str(page.image).split('.')
        newimg = imgsplt[0] + 's.' + imgsplt[1]
        page.image_small = newimg
        page.save()


def import_data(apps, schemd_editor) -> None:
    addsmallimage(apps)




class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0012_auto_20160303_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_small',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.RunPython(import_data)
    ]
