# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0023_auto_20161002_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_type_httpRequest',
        ),
    ]
