# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0024_remove_page_image_type_httprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='coord_transform_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
