# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 01:20
#
#   This restores the coord_transform_type value
#   Unfortunately, we lost this value
#
##################################################
from __future__ import unicode_literals

from django.db import migrations, models

from os.path import isfile
from ..models import Character

def infer_box_transform_type(apps) -> None:
    Page = apps.get_model("calligraphy", "Page")
    Char = apps.get_model("calligraphy", "Character")
    pages = Page.objects.all()
    for page in pages:
        chars = Char.objects.filter(parent_page=page)
        if(len(chars) > 0):
            good_transform = True
            for char in chars:
                charstr = Character.get_image(char)
                char_split = charstr.split('.')
                char_hirez = char_split[0] + '.hi-rez.' + char_split[1]
                print(char_hirez)
                if(not isfile(char_hirez)):
                    good_transform = False;
            page.i_valid_transform = good_transform
            page.save()
            
                

def do_stuff(apps, schemd_editor) -> None:
    infer_box_transform_type(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0025_page_coord_transform_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='coord_transform_type',
        ),
        migrations.AddField(
            model_name='page',
            name='i_valid_transform',
            field=models.NullBooleanField(default=None),
            preserve_default=False,
        ),
        migrations.RunPython(do_stuff)
    ] 
