# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 01:54
#
#   
#
##################################################
from __future__ import unicode_literals

from django.db import migrations

def infer_box_transform_type(apps) -> None:
    

def do_stuff(apps, schemd_editor) -> None:
    make_high_rez(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0025_page_coord_transform_type'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
