# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 01:59
#
# Corrects the null links in page, by using children
#
###############################################################################################
from __future__ import unicode_literals

from django.db import migrations

def fix_nulls(apps) -> None:
    Page = apps.get_model("calligraphy", "Page")
    Char = apps.get_model("calligraphy", "Character")
    pages = Page.objects.all()
    for page in pages:
        if page.parent_work is None:
            chars = Char.objects.filter(parent_page=page)
            root_work = None
            root_name = None
            for char in chars:
                if(root_work is None):
                    root_work = char.parent_work
                    root_name = char.parent_work_name
                else:
                    if root_work is not char.parent_work:
                        raise(Exception("Data Inconsistency between characters and pages"))
            page.parent_work = root_work
            page.parent_work_name = root_name


def do_stuff(apps, schemd_editor) -> None:
    fix_nulls(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0026_auto_20161011_1820'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
