# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 04:20
#
# Restores data for the transform type we lost earlier
#
#####################################################
from __future__ import unicode_literals

from django.db import migrations, models

def restore_transform_type(apps) -> None:
    Page = apps.get_model("calligraphy", "Page")
    Char = apps.get_model("calligraphy", "Character")
    pages = Page.objects.all()
    for page in pages:
        chars = Char.objects.filter(parent_page=page)
        if len(chars) > 0:
            fchar = chars[0]
            if ((fchar.x1 / 5) == int(str(fchar.image).split('(')[1].split(',')[0])):
                page.i_transform_type_new = True
            else:
                page.i_transform_type_new = False
            page.save()

def do_stuff(apps, schemd_editor) -> None:
    restore_transform_type(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0030_auto_20161014_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='i_transform_type_new',
            field=models.NullBooleanField(),
        ), migrations.RunPython(do_stuff)
    ] 
