# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 02:38
from __future__ import unicode_literals

from django.db import migrations, models
from PIL import Image


def set_thumbs_size(apps) -> None:
    Character = apps.get_model('calligraphy', 'Character')
    chars = Character.objects.all()
    for char in chars:
        print(str(char.image_thumb))
        img = Image.open(str(char.image_thumb)).size
        char.image_thumb_y = img[0]
        char.image_thumb_x = img[1]
        char.save()

def do_stuff(apps, schemd_editor) -> None:
    set_thumbs_size(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0036_run_cropper'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_thumb_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='image_thumb_y',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(do_stuff)
    ]
