# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
from PIL import Image
from pathlib import Path


def make_thumbnails(apps) -> None:
    Character = apps.get_model('calligraphy', 'Character')
    chars = Character.objects.all()
    for char in chars:
        fileptr = char.image_high_rez
        if not bool(fileptr):
            make_hi_rez(char, char.parent_page)
        fileptr.close()
        im = Image.open(str(char.image_high_rez))
        width = int(float(char.x2 - char.x1) / float(char.y2 - char.y1) * 100)
        img_thumb = im.resize((width, 100), Image.BOX)
        img_thumb_name = str(char.image).strip('jpgpntif') + 'thumb.png'
        img_thumb.save(img_thumb_name, 'PNG')
        img_thumb.close()
        char.image_thumb = img_thumb_name
        char.save()

def do_stuff(apps, schemd_editor) -> None:
    make_thumbnails(apps)




class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0037_auto_20161102_1938'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
