# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models
from PIL import Image


def set_thumbs_size(apps) -> None:
    Character = apps.get_model('calligraphy', 'Character')
    chars = Character.objects.all()
    for char in chars:
        print(str(char.image_thumb))
        img = Image.open(str(char.image_thumb)).size
        char.image_thumb_y = img[0]
        char.image_thumb_x = img[1]
        char.save()

def do_stuff(apps, schemd_editor) -> None:
    set_thumbs_size(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0038_auto_20161103_1207'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
