# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 11:01
#
# Goes through and oppulates transform type according to the following
#
# None:  No chars
# Old:   Old Transform Type
# New:   New Transform Type
#
######################################################
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0045_auto_20161201_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='transform_type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
