# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0047_auto_20170107_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='i_transform_type_new',
        ),
        migrations.RemoveField(
            model_name='page',
            name='i_transform_validated',
        ),
        migrations.RemoveField(
            model_name='page',
            name='i_valid_transform',
        ),
    ]
