# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0048_auto_20170107_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToFindMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page')),
            ],
        ),
    ]
