# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:36
#
#  Gathers list of chars that I have yet to find the correct multipliers for
#
###########################################################


from __future__ import unicode_literals

from django.db import migrations, models


def buildList(apps) -> None:
    PageMultiplier = apps.get_model('calligraphy', 'PageMultiplier')
    PageList = apps.get_model('calligraphy', 'ToFindMultiplier')
    
    pages = PageMultiplier.objects.all()
    
    gotList = []
    
    for page in pages:
        pId = page.parent_page.id
        if pId not in gotList:
            gotList.append(pId)
            print(pId)
            PageList(page_id=page.parent_page).save()


def do_stuff(apps, schemd_editor) -> None:
    buildList(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0049_tofindmultiplier'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
