# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0050_auto_20170107_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='collection',
            field=models.IntegerField(default=0),
        ),
    ]
