# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0052_auto_20170117_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemultiplier',
            name='parent_page',
        ),
        migrations.DeleteModel(
            name='PageMultiplier',
        ),
    ]
