# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0053_auto_20170117_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tofindmultiplier',
            name='times_reviewed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
