# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calligraphy', '0054_tofindmultiplier_times_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_offset', models.FloatField()),
                ('set_chars', models.ManyToManyField(to='calligraphy.Character')),
            ],
        ),
        migrations.CreateModel(
            name='UserSuppliedPageMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='charset',
            name='userSupplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.UserSuppliedPageMultiplier'),
        ),
    ]
