# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0055_auto_20170118_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charset',
            old_name='set_offset',
            new_name='set_offset_x',
        ),
        migrations.AddField(
            model_name='charset',
            name='set_offset_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
