# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0056_auto_20170118_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='charset',
            name='set_has_problems',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
