# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0057_charset_set_has_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='charset',
            name='image_rotation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
