# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0058_charset_image_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charset',
            name='set_chars',
        ),
    ]
