# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0059_remove_charset_set_chars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charset',
            name='image_rotation',
        ),
        migrations.AddField(
            model_name='usersuppliedpagemultiplier',
            name='image_rotation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
