# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0061_auto_20170128_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tofindmultiplier',
            name='times_reviewed',
        ),
    ]
