# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0062_remove_tofindmultiplier_times_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='charset',
            name='set_chars',
            field=models.ManyToManyField(to='calligraphy.Character'),
        ),
    ]
