# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0073_character_supplied_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToCountCharactersWBoxes',
            new_name='ToDrawBoxesWBoxes',
        ),
        migrations.RenameModel(
            old_name='toCountCharactersWoBoxes',
            new_name='ToDrawBoxesWoBoxes',
        ),
    ]
