# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 00:08
#
# This one goes through the to-draw list and gets rid of over-segmented images
#
#
#################################################################################################
from __future__ import unicode_literals

from django.db import migrations

def remove_duplicates(apps) -> None:
    UserMult = apps.get_model('calligraphy', 'UserSuppliedPageMultiplier')
    for doIDrawBox in apps.get_model('calligraphy', 'ToDrawBoxesWBoxes').objects.all():
        if len(UserMult.objects.filter(page_id=doIDrawBox.toCheck)) is not 0:
            doIDrawBox.delete()
        

def do_stuff(apps, schemd_editor) -> None:
    remove_duplicates(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0074_auto_20170223_1727'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
