# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0075_auto_20170224_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_bad',
            field=models.BooleanField(default=False),
        ),
    ]
