# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0078_char_location_update_should_be_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='image_thumb_y',
            new_name='image_height',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='image_thumb_x',
            new_name='image_width',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image_high_rez',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image_thumb',
        ),
    ]
