# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 17:21
#
# This one corrects the image height and width
#
######################################################
from __future__ import unicode_literals

from django.db import migrations
from PIL import Image as im


def do_stuff(apps, schemd_editor) -> None:
    for char in apps.get_model('calligraphy', 'Character').objects.all():
        img = im.open(str(char.image))
        char.image_height = img.height;
        char.image_width = img.width;
        img.close()
        char.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0079_auto_20170306_1710'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
