# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calligraphy', '0081_auto_20170321_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagForReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page')),
            ],
        ),
        migrations.AlterField(
            model_name='char_location_update',
            name='x1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='char_location_update',
            name='x2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='char_location_update',
            name='y1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='char_location_update',
            name='y2',
            field=models.IntegerField(),
        ),
    ]
