# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 13:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calligraphy', '0082_auto_20170321_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_orig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=64)),
                ('parent_work_name', models.CharField(blank=True, max_length=64)),
                ('mark', models.CharField(blank=True, max_length=64)),
                ('x1', models.IntegerField(blank=True)),
                ('y1', models.IntegerField(blank=True)),
                ('x2', models.IntegerField(blank=True)),
                ('y2', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('image_width', models.IntegerField(default=0)),
                ('image_height', models.IntegerField(default=0)),
                ('parent_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Author')),
                ('parent_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page')),
                ('parent_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Work')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
