# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0084_auto_20170322_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char_location_update',
            name='supplied_by',
        ),
        migrations.RemoveField(
            model_name='char_location_update',
            name='target_char',
        ),
        migrations.DeleteModel(
            name='Char_location_update',
        ),
    ]
