# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0085_auto_20170322_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovalidateoffsets',
            name='toCheck',
        ),
        migrations.DeleteModel(
            name='ToValidateOffsets',
        ),
    ]
