# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0086_auto_20170322_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_parents',
            field=models.ManyToManyField(to='calligraphy.Character_orig'),
        ),
    ]
