# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0090_auto_20170322_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charset',
            name='set_chars',
        ),
    ]
