# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 19:04
#
# adjust coordinates for all characters, do-over because I messed it up last time
#
######################################################################

from __future__ import unicode_literals

from django.db import migrations

def fix_coordinates(apps) -> None:
    Chars_back = apps.get_model('calligraphy', 'Character_orig')
    Chars =      apps.get_model('calligraphy', 'Character')
    CharSet =    apps.get_model('calligraphy', 'CharSet')
    
    for charset in CharSet.objects.all():
        for ochar in charset.set_chars_orig.all():
            char = Chars.objects.get(id=ochar.id)
            coords = str(char.image).split('(')[1].split(')')[0].split(',')
            x1 = int(coords[0]) 
            y1 = int(coords[1])
            x2 = int(coords[2])
            y2 = int(coords[3])
            
            char.x1 = int(x1 * charset.set_offset_x)
            char.x2 = int(x2 * charset.set_offset_x)
            char.y1 = int(y1 * charset.set_offset_y)
            char.y2 = int(y2 * charset.set_offset_y)
            char.save()
            

def do_stuff(apps, schemd_editor) -> None:
    fix_coordinates(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0092_auto_20170322_1850'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
