# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 20:58
#
# Changes image size to accomodate rotation
#
from __future__ import unicode_literals

from django.db import migrations
from PIL import Image

def do_things(apps) -> None:
    pagenums = [11837, 11953] # These pages turned 90deg
    Page = apps.get_model('calligraphy', 'Page');
    for pagenum in pagenums:
        page = Page.objects.get(id=pagenum)
        img = Image.open(str(page.image))
        page.image_width = img.size[0]
        page.image_length = img.size[1]
        page.save()
            

def do_stuff(apps, schemd_editor) -> None:
    do_things(apps)



class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0094_auto_20170322_2050'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
