# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0095_auto_20170322_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_bad',
        ),
    ]
