# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0098_auto_20170323_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='char_parents',
        ),
    ]
