# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:51
#
# This one goes through and marks all scanned pages as copyrighted.
#
#
###################################################################


from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor) -> None:
    for page in apps.get_model('calligraphy', 'Page').objects.all():
        if 'scanned' in str(page.image):
            page.has_copyright_restrictions = True
            page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0101_page_has_copyright_restrictions'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
