# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 03:36
#
# Goes through and builds detect box based on read values
#
######################################################################

from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor) -> None:
    print("do nothing")


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0107_detectedbox'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
