# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 15:28
from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor) -> None:
    print("Doint Nothing.")


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0108_auto_20170906_0336'),
        ('calligraphy', '0001_detectedbox_black_chars'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
