# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0109_merge_20170906_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_works',
            field=models.BooleanField(default=True),
        ),
    ]
