# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 10:32
from __future__ import unicode_literals

from django.db import migrations
from os import path

def do_stuff(apps, schemd_editor) -> None:
    Pages = apps.get_model('calligraphy', 'Page').objects.all()
    for page in Pages:
        filename = str(page.image)
        is_file = path.isfile(str(page.image))
        print(str(is_file) + " " + filename)
        page.image_works = is_file
        page.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0110_page_image_works'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
