# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0112_auto_20170908_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='inside_selected_box',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
