# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0113_detectedbox_inside_selected_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedbox',
            old_name='inside_selected_box',
            new_name='inside_validated_box',
        ),
    ]
