# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0114_auto_20170911_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='inside_orig_box',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
