# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0117_auto_20170911_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='li_threshold_bottom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedbox',
            name='li_threshold_top',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
