# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 12:30
#
# One off to erase data inside the flagged for review table
#
####################################################
from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor) -> None:
    for label in apps.get_model('calligraphy', 'FlagForReview').objects.all():
        label.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0121_auto_20170914_2344'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
