# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 12:35
#
#
# Goes through and gets rid of character data for some of the pages prior to re-do
#
#######################################################
from __future__ import unicode_literals

from django.db import migrations

PAGES = [4745, 13639, 12643, 10508, 6560, 6337, 5803, 10811, 8155, 11328, 9572, 15045, 4747, 19966, 12713, 10868, 4745, 6146, 6579, 19212, 10883]

def do_stuff(apps, schemd_editor) -> None:
    Pages = apps.get_model('calligraphy', 'Page').objects
    DetectedBox = apps.get_model('calligraphy', 'DetectedBox').objects
    for page_num in PAGES:
        page = Pages.get(id=page_num)
        for thisbox in DetectedBox.filter(parent_page=page):
            thisbox.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0122_auto_20170915_1230'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
