# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0124_auto_20170915_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedbox',
            name='inside_orig_box',
        ),
        migrations.RemoveField(
            model_name='detectedbox',
            name='inside_validated_box',
        ),
        migrations.AddField(
            model_name='detectedbox',
            name='percent_inside_currated_box',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedbox',
            name='percent_inside_orig_box',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
