# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0130_remove_detectedbox_percent_inside_currated_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedbox',
            name='inside_orig_box',
            field=models.BooleanField(),
        ),
    ]
