# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 00:03
#
# Establishes boolean values for being inside the box or outside
#
#############################################################


from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor) -> None:
    Pages = apps.get_model('calligraphy', 'Page').objects
    DetectedBox = apps.get_model('calligraphy', 'DetectedBox').objects
    PagesHaveChars = apps.get_model('calligraphy', 'PagesHaveChars').objects
    for thisPage in PagesHaveChars.all():
        curPage = Pages.get(id=thisPage.haveChars.id)
        features  = DetectedBox.filter(parent_page=curPage)
        print("PageId: " + str(thisPage.haveChars.id) + " Features: " + str(len(features)))
        for feature in features:
            if feature.percent_inside_orig_box >=80:
                feature.inside_orig_box = True
            else:
                feature.inside_orig_box = False
            feature.save(update_fields=['inside_orig_box'])

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0131_auto_20170918_2358'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
