# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0135_remove_detectedbox_percent_inside_orig_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='area_norm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
