# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0137_auto_20170919_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedbox',
            name='area',
        ),
    ]
