# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0138_remove_detectedbox_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='convex_area_norm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
