# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 00:01
#
# Normalizes eccentricity
#
#############################################################


from __future__ import unicode_literals

from django.db import migrations, connection

def do_stuff(apps, schemd_editor) -> None:
    with connection.cursor() as cursor:
        cursor.execute("UPDATE calligraphy_detectedbox SET eccentricity_norm = CAST( eccentricity * 2147483647 AS int )")


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0142_detectedbox_eccentricity_norm'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
