# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0144_remove_detectedbox_eccentricity'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='extant_norm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
