# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0145_detectedbox_extant_norm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedbox',
            name='extant',
        ),
    ]
