# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 00:34
#
# Normalizes Solidity
#
#############################################################


from __future__ import unicode_literals

from django.db import migrations, connection

def do_stuff(apps, schemd_editor) -> None:
    with connection.cursor() as cursor:
        cursor.execute("UPDATE calligraphy_detectedbox SET solidity_norm = CAST( solidity * 2147483647 AS int )")

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0147_detectedbox_solidity_norm'),
    ]

    operations = [  migrations.RunPython(do_stuff)
    ]
