# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0149_remove_detectedbox_solidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='orientation_norm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
