# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 01:26
#
# Normalizes li_threshold_bottom
#
#############################################################

from __future__ import unicode_literals

from django.db import migrations, connection

def do_stuff(apps, schemd_editor) -> None:
    with connection.cursor() as cursor:
        cursor.execute("UPDATE calligraphy_detectedbox SET li_threshold_bottom_norm = CAST( li_threshold_bottom * 8421504 AS int )")

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0153_detectedbox_li_threshold_bottom_norm'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
