# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0161_remove_detectedbox_local_centroid_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='local_centroid_y_norm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
