# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 02:50
#
# Normalizes  major and monor axis lengths
#
########################################################
from __future__ import unicode_literals

from django.db import migrations, connection
import math

def do_stuff(apps, schemd_editor) -> None:
    Pages = apps.get_model('calligraphy', 'Page').objects
    HaveChars = apps.get_model('calligraphy', 'PagesHaveChars').objects
    DetectedBox = apps.get_model('calligraphy', 'DetectedBox').objects
    with connection.cursor() as cursor:
        for thisPage in HaveChars.all():
            len_x = thisPage.x2 - thisPage.x1
            len_y = thisPage.y2 - thisPage.y1
            max_length = math.sqrt(math.pow(len_x, 2) + math.pow(len_y, 2))
            max_mult = 1 / max_length * 2147483647 / 2
            print("PageId: " + str(thisPage.haveChars.id))
            cursor.execute("UPDATE calligraphy_detectedbox SET maxor_axis_length_norm = CAST( major_axis_length * %s AS int )  WHERE parent_page_id = %s", [max_mult, thisPage.haveChars.id])
            cursor.execute("UPDATE calligraphy_detectedbox SET minor_axis_length_norm = CAST( minor_axis_length * %s AS int )  WHERE parent_page_id = %s", [max_mult, thisPage.haveChars.id])

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0165_auto_20170920_0242'),
    ]

    operations = [  migrations.RunPython(do_stuff)
    ]
