# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0168_auto_20170922_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedbox',
            name='extant_norm',
        ),
    ]
