# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0169_remove_detectedbox_extant_norm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedbox',
            old_name='maxor_axis_length_norm',
            new_name='major_axis_length_norm',
        ),
    ]
