# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0170_auto_20170922_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedbox',
            name='convex_area_norm',
        ),
    ]
