# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0171_remove_detectedbox_convex_area_norm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoScanned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toCheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page')),
            ],
        ),
    ]
