# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 21:11
#
# Addes scanned image to todo list so I can get my validation set up and running
#
###########################################################

from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor) -> None:
    Pages = apps.get_model('calligraphy', 'Page').objects
    NewToDo = apps.get_model('calligraphy', 'TodoScanned')
    for page in Pages.filter(has_copyright_restrictions=True):
        NewToDo(toCheck=page).save()

class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0172_todoscanned'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
