# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 00:07
#
# Goes through and builds normalized features for validation set
#
##########################################################################################
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0173_auto_20170923_2111'),
    ]

    operations = [
    ]
