# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0174_auto_20170925_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='predict_good_using_good',
            field=models.NullBooleanField(),
        ),
    ]
