# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0175_detectedbox_predict_good_using_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='predict_good_using_bad',
            field=models.NullBooleanField(),
        ),
    ]
