# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0176_detectedbox_predict_good_using_bad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedbox',
            old_name='predict_good_using_bad',
            new_name='predict_using_bad',
        ),
        migrations.RenameField(
            model_name='detectedbox',
            old_name='predict_good_using_good',
            new_name='predict_using_good',
        ),
    ]
