# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 15:34
#
#
# Goes through and collects statistics for prediction
#
##########################################################
from __future__ import unicode_literals

from django.db import migrations

def do_stuff(apps, schemd_editor):
    num_boxes = 0
    predict_good_true__pos = 0
    predict_good_true__neg = 0
    predict_good_false_pos = 0
    predict_good_false_neg = 0
    predict_bad__true__pos = 0
    predict_bad__true__neg = 0
    predict_bad__false_pos = 0
    predict_bad__false_neg = 0
    DetectedBox = apps.get_model('calligraphy', 'DetectedBox').objects
    pages_scn = apps.get_model('calligraphy', 'Page').objects.filter(has_copyright_restrictions=True)
    for page in pages_scn:
        boxes = DetectedBox.filter(parent_page=page)
        for box in boxes:
            num_boxes += 1
            if box.inside_currated_box:
                if box.predict_using_good:
                    predict_good_true__pos += 1
                else:
                    predict_good_false_neg += 1
                if box.predict_using_bad:
                    predict_bad__true__pos += 1
                else:
                    predict_bad__false_neg += 1
            else:
                if box.predict_using_good:
                    predict_good_false_pos += 1
                else:
                    predict_good_true__neg += 1
                if box.predict_using_bad:
                    predict_bad__false_pos += 1
                else:
                    predict_bad__true__neg += 1
    print()
    print("predict_good_true__pos: " + str(predict_good_true__pos))
    print("predict_good_true__neg: " + str(predict_good_true__neg))
    print("predict_good_false_pos: " + str(predict_good_false_pos))
    print("predict_good_false_neg: " + str(predict_good_false_neg))
    print("predict_bad__true__pos: " + str(predict_bad__true__pos))
    print("predict_bad__true__neg: " + str(predict_bad__true__neg))
    print("predict_bad__false_pos: " + str(predict_bad__false_pos))
    print("predict_bad__false_neg: " + str(predict_bad__false_neg))
    print("Num Boxes: " + str(num_boxes))
    raise Exception("Stop Here")


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0179_auto_20170930_1534'),
    ]

    operations = [  migrations.RunPython(do_stuff)
    ]
