# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0193_auto_20171002_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcombinedbox',
            name='based_on_bad_predictor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedcombinedbox',
            name='based_on_good_predictor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectedcombinedbox',
            name='based_on_no_predictor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
