# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0220_auto_20171002_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcombinedbox',
            name='demonstration',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
