# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0225_auto_20171003_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='black_chars',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
