# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0227_auto_20171008_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedbox',
            name='black_chars',
        ),
    ]
