# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0229_auto_20171008_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Author'),
        ),
    ]
