# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0232_auto_20171012_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='parent_char',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
