# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0234_remove_detectedbox_parent_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedbox',
            name='parent_char',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Character'),
        ),
    ]
