# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 23:27
#
#
# Goes through an builds pairs of features and whether they are part of the same char
#
###########################################################
from __future__ import unicode_literals

from django.db import migrations
import numpy as np
 
class Box(object):
    def __init__(self, parent):
        self.parent = parent
        self.nearby_boxes = []
        self.y_range = set()
        for i in range(parent.y1, parent.y2):
            self.y_range.add(i)
 
class BoxIndex(object):
    def __init__(self):
        self.boxes_id = set()
        
NUM_NEARBY_GLYPHS = 1

def do_stuff(apps, schemd_editor):
    Pages = apps.get_model('calligraphy', 'Page').objects
    DetectedBox = apps.get_model('calligraphy', 'DetectedBox').objects
    PagesHaveChars = apps.get_model('calligraphy', 'PagesHaveChars').objects
    page_count = len(PagesHaveChars.all())
    count = 0
    for thisPage in PagesHaveChars.all():
        count += 1
        print(str(count) + " / " + str(page_count))
        cur_page = Pages.get(id=thisPage.haveChars.id)
        boxes  = DetectedBox.filter(parent_page=cur_page)
        x_index = dict()
        box_by_id = dict()
        box_list = []
        my_x_boxes = set()
        for i in range(cur_page.image_length):
            x_index[i] = BoxIndex()
        for box in boxes:
            mybox = Box(box)
            box_list.append(mybox)
            box_by_id[box.id] = mybox
            for i in range(box.x1, box.x2):
                x_index[i].boxes_id.add(box.id)
        for box in box_list:
            cur_x = box.parent.x2
            cur_y = box.parent.y2
            edge_right = False
            edge_bottom = False
            chars_x = set()
            chars_x_ys = set()
            chars_confirmed = set()
            y_range = set()
            while len(chars_confirmed) < NUM_NEARBY_GLYPHS and not (edge_right and edge_bottom):
                if not edge_right:
                    cur_x += 1
                    if cur_x > cur_page.image_width:
                        edge_right = True
                    else:
                        if len(x_index[cur_x].boxes_id):
                            diff = x_index[cur_x].boxes_id.difference(chars_x)
                            if diff:
                                chars_x.update(diff)
                                for dif in diff:
                                    chars_x_ys.update(box_by_id[dif].y_range)
                if not edge_bottom:
                    cur_y += 1
                    if cur_y > cur_page.image_length:
                        edge_bottom = True
                    else:
                        y_range.add(cur_y)
                if chars_x_ys.intersection(y_range):
                    for char_cur in chars_x:
                        if box_by_id[char_cur].y_range.intersection(y_range):
                            chars_confirmed.add(char_cur)
            print(len(chars_confirmed))
    raise Exception("stop here")


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0236_auto_20171027_0008'),
    ]

    operations = [ migrations.RunPython(do_stuff)
    ]
