# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 20:56
#
# Had to delete and start from scratch because the thing was taking too long to update
#
#######################################################
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0239_boxedges_same_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxedges',
            name='edge_to',
        ),
        migrations.DeleteModel(
            name='BoxEdges',
        ),
    ]
