# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calligraphy', '0240_auto_20171127_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxEdges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_from', models.IntegerField()),
                ('edge_right', models.BooleanField()),
                ('same_character', models.BooleanField()),
                ('edge_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.DetectedBox')),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calligraphy.Page')),
            ],
        ),
    ]
